//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DB_TRACNGHIEMModel", "FK_TB_CAUHOI_TB_MONTHI", "TB_MONTHI", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Data_Tier.TB_MONTHI), "TB_CAUHOI", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Tier.TB_CAUHOI), true)]
[assembly: EdmRelationshipAttribute("DB_TRACNGHIEMModel", "FK_TB_CAUHOI_TB_NHANVIEN", "TB_NHANVIEN", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Data_Tier.TB_NHANVIEN), "TB_CAUHOI", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Tier.TB_CAUHOI), true)]
[assembly: EdmRelationshipAttribute("DB_TRACNGHIEMModel", "FK_TB_DAPAN_TB_CAUHOI", "TB_CAUHOI", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Tier.TB_CAUHOI), "TB_DAPAN", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Tier.TB_DAPAN), true)]
[assembly: EdmRelationshipAttribute("DB_TRACNGHIEMModel", "FK_TB_KETQUA_TB_MONTHI", "TB_MONTHI", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Data_Tier.TB_MONTHI), "TB_KETQUA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Tier.TB_KETQUA), true)]
[assembly: EdmRelationshipAttribute("DB_TRACNGHIEMModel", "FK_TB_KETQUA_TB_THISINH", "TB_THISINH", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Data_Tier.TB_THISINH), "TB_KETQUA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Tier.TB_KETQUA), true)]

#endregion

namespace Data_Tier
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DB_TRACNGHIEMEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DB_TRACNGHIEMEntities object using the connection string found in the 'DB_TRACNGHIEMEntities' section of the application configuration file.
        /// </summary>
        public DB_TRACNGHIEMEntities() : base("name=DB_TRACNGHIEMEntities", "DB_TRACNGHIEMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB_TRACNGHIEMEntities object.
        /// </summary>
        public DB_TRACNGHIEMEntities(string connectionString) : base(connectionString, "DB_TRACNGHIEMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB_TRACNGHIEMEntities object.
        /// </summary>
        public DB_TRACNGHIEMEntities(EntityConnection connection) : base(connection, "DB_TRACNGHIEMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_CAUHOI> TB_CAUHOI
        {
            get
            {
                if ((_TB_CAUHOI == null))
                {
                    _TB_CAUHOI = base.CreateObjectSet<TB_CAUHOI>("TB_CAUHOI");
                }
                return _TB_CAUHOI;
            }
        }
        private ObjectSet<TB_CAUHOI> _TB_CAUHOI;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_DAPAN> TB_DAPAN
        {
            get
            {
                if ((_TB_DAPAN == null))
                {
                    _TB_DAPAN = base.CreateObjectSet<TB_DAPAN>("TB_DAPAN");
                }
                return _TB_DAPAN;
            }
        }
        private ObjectSet<TB_DAPAN> _TB_DAPAN;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_KETQUA> TB_KETQUA
        {
            get
            {
                if ((_TB_KETQUA == null))
                {
                    _TB_KETQUA = base.CreateObjectSet<TB_KETQUA>("TB_KETQUA");
                }
                return _TB_KETQUA;
            }
        }
        private ObjectSet<TB_KETQUA> _TB_KETQUA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_MONTHI> TB_MONTHI
        {
            get
            {
                if ((_TB_MONTHI == null))
                {
                    _TB_MONTHI = base.CreateObjectSet<TB_MONTHI>("TB_MONTHI");
                }
                return _TB_MONTHI;
            }
        }
        private ObjectSet<TB_MONTHI> _TB_MONTHI;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_NHANVIEN> TB_NHANVIEN
        {
            get
            {
                if ((_TB_NHANVIEN == null))
                {
                    _TB_NHANVIEN = base.CreateObjectSet<TB_NHANVIEN>("TB_NHANVIEN");
                }
                return _TB_NHANVIEN;
            }
        }
        private ObjectSet<TB_NHANVIEN> _TB_NHANVIEN;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_THISINH> TB_THISINH
        {
            get
            {
                if ((_TB_THISINH == null))
                {
                    _TB_THISINH = base.CreateObjectSet<TB_THISINH>("TB_THISINH");
                }
                return _TB_THISINH;
            }
        }
        private ObjectSet<TB_THISINH> _TB_THISINH;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_CAUHOI EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_CAUHOI(TB_CAUHOI tB_CAUHOI)
        {
            base.AddObject("TB_CAUHOI", tB_CAUHOI);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_DAPAN EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_DAPAN(TB_DAPAN tB_DAPAN)
        {
            base.AddObject("TB_DAPAN", tB_DAPAN);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_KETQUA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_KETQUA(TB_KETQUA tB_KETQUA)
        {
            base.AddObject("TB_KETQUA", tB_KETQUA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_MONTHI EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_MONTHI(TB_MONTHI tB_MONTHI)
        {
            base.AddObject("TB_MONTHI", tB_MONTHI);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_NHANVIEN EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_NHANVIEN(TB_NHANVIEN tB_NHANVIEN)
        {
            base.AddObject("TB_NHANVIEN", tB_NHANVIEN);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_THISINH EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_THISINH(TB_THISINH tB_THISINH)
        {
            base.AddObject("TB_THISINH", tB_THISINH);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_TRACNGHIEMModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_TRACNGHIEMModel", Name="TB_CAUHOI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_CAUHOI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_CAUHOI object.
        /// </summary>
        /// <param name="mACAUHOI">Initial value of the MACAUHOI property.</param>
        public static TB_CAUHOI CreateTB_CAUHOI(global::System.String mACAUHOI)
        {
            TB_CAUHOI tB_CAUHOI = new TB_CAUHOI();
            tB_CAUHOI.MACAUHOI = mACAUHOI;
            return tB_CAUHOI;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MACAUHOI
        {
            get
            {
                return _MACAUHOI;
            }
            set
            {
                if (_MACAUHOI != value)
                {
                    OnMACAUHOIChanging(value);
                    ReportPropertyChanging("MACAUHOI");
                    _MACAUHOI = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MACAUHOI");
                    OnMACAUHOIChanged();
                }
            }
        }
        private global::System.String _MACAUHOI;
        partial void OnMACAUHOIChanging(global::System.String value);
        partial void OnMACAUHOIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOIDUNG
        {
            get
            {
                return _NOIDUNG;
            }
            set
            {
                OnNOIDUNGChanging(value);
                ReportPropertyChanging("NOIDUNG");
                _NOIDUNG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOIDUNG");
                OnNOIDUNGChanged();
            }
        }
        private global::System.String _NOIDUNG;
        partial void OnNOIDUNGChanging(global::System.String value);
        partial void OnNOIDUNGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MAMON
        {
            get
            {
                return _MAMON;
            }
            set
            {
                OnMAMONChanging(value);
                ReportPropertyChanging("MAMON");
                _MAMON = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MAMON");
                OnMAMONChanged();
            }
        }
        private global::System.String _MAMON;
        partial void OnMAMONChanging(global::System.String value);
        partial void OnMAMONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MANHANVIEN
        {
            get
            {
                return _MANHANVIEN;
            }
            set
            {
                OnMANHANVIENChanging(value);
                ReportPropertyChanging("MANHANVIEN");
                _MANHANVIEN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MANHANVIEN");
                OnMANHANVIENChanged();
            }
        }
        private global::System.String _MANHANVIEN;
        partial void OnMANHANVIENChanging(global::System.String value);
        partial void OnMANHANVIENChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_TRACNGHIEMModel", "FK_TB_CAUHOI_TB_MONTHI", "TB_MONTHI")]
        public TB_MONTHI TB_MONTHI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_MONTHI>("DB_TRACNGHIEMModel.FK_TB_CAUHOI_TB_MONTHI", "TB_MONTHI").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_MONTHI>("DB_TRACNGHIEMModel.FK_TB_CAUHOI_TB_MONTHI", "TB_MONTHI").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_MONTHI> TB_MONTHIReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_MONTHI>("DB_TRACNGHIEMModel.FK_TB_CAUHOI_TB_MONTHI", "TB_MONTHI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_MONTHI>("DB_TRACNGHIEMModel.FK_TB_CAUHOI_TB_MONTHI", "TB_MONTHI", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_TRACNGHIEMModel", "FK_TB_CAUHOI_TB_NHANVIEN", "TB_NHANVIEN")]
        public TB_NHANVIEN TB_NHANVIEN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_NHANVIEN>("DB_TRACNGHIEMModel.FK_TB_CAUHOI_TB_NHANVIEN", "TB_NHANVIEN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_NHANVIEN>("DB_TRACNGHIEMModel.FK_TB_CAUHOI_TB_NHANVIEN", "TB_NHANVIEN").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_NHANVIEN> TB_NHANVIENReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_NHANVIEN>("DB_TRACNGHIEMModel.FK_TB_CAUHOI_TB_NHANVIEN", "TB_NHANVIEN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_NHANVIEN>("DB_TRACNGHIEMModel.FK_TB_CAUHOI_TB_NHANVIEN", "TB_NHANVIEN", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_TRACNGHIEMModel", "FK_TB_DAPAN_TB_CAUHOI", "TB_DAPAN")]
        public EntityCollection<TB_DAPAN> TB_DAPAN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_DAPAN>("DB_TRACNGHIEMModel.FK_TB_DAPAN_TB_CAUHOI", "TB_DAPAN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_DAPAN>("DB_TRACNGHIEMModel.FK_TB_DAPAN_TB_CAUHOI", "TB_DAPAN", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_TRACNGHIEMModel", Name="TB_DAPAN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_DAPAN : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_DAPAN object.
        /// </summary>
        /// <param name="mACAUHOI">Initial value of the MACAUHOI property.</param>
        /// <param name="mADAPAN">Initial value of the MADAPAN property.</param>
        public static TB_DAPAN CreateTB_DAPAN(global::System.String mACAUHOI, global::System.String mADAPAN)
        {
            TB_DAPAN tB_DAPAN = new TB_DAPAN();
            tB_DAPAN.MACAUHOI = mACAUHOI;
            tB_DAPAN.MADAPAN = mADAPAN;
            return tB_DAPAN;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MACAUHOI
        {
            get
            {
                return _MACAUHOI;
            }
            set
            {
                if (_MACAUHOI != value)
                {
                    OnMACAUHOIChanging(value);
                    ReportPropertyChanging("MACAUHOI");
                    _MACAUHOI = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MACAUHOI");
                    OnMACAUHOIChanged();
                }
            }
        }
        private global::System.String _MACAUHOI;
        partial void OnMACAUHOIChanging(global::System.String value);
        partial void OnMACAUHOIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MADAPAN
        {
            get
            {
                return _MADAPAN;
            }
            set
            {
                if (_MADAPAN != value)
                {
                    OnMADAPANChanging(value);
                    ReportPropertyChanging("MADAPAN");
                    _MADAPAN = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MADAPAN");
                    OnMADAPANChanged();
                }
            }
        }
        private global::System.String _MADAPAN;
        partial void OnMADAPANChanging(global::System.String value);
        partial void OnMADAPANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOIDUNGDAPAN
        {
            get
            {
                return _NOIDUNGDAPAN;
            }
            set
            {
                OnNOIDUNGDAPANChanging(value);
                ReportPropertyChanging("NOIDUNGDAPAN");
                _NOIDUNGDAPAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOIDUNGDAPAN");
                OnNOIDUNGDAPANChanged();
            }
        }
        private global::System.String _NOIDUNGDAPAN;
        partial void OnNOIDUNGDAPANChanging(global::System.String value);
        partial void OnNOIDUNGDAPANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KIEUDAPAN
        {
            get
            {
                return _KIEUDAPAN;
            }
            set
            {
                OnKIEUDAPANChanging(value);
                ReportPropertyChanging("KIEUDAPAN");
                _KIEUDAPAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KIEUDAPAN");
                OnKIEUDAPANChanged();
            }
        }
        private global::System.String _KIEUDAPAN;
        partial void OnKIEUDAPANChanging(global::System.String value);
        partial void OnKIEUDAPANChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_TRACNGHIEMModel", "FK_TB_DAPAN_TB_CAUHOI", "TB_CAUHOI")]
        public TB_CAUHOI TB_CAUHOI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_CAUHOI>("DB_TRACNGHIEMModel.FK_TB_DAPAN_TB_CAUHOI", "TB_CAUHOI").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_CAUHOI>("DB_TRACNGHIEMModel.FK_TB_DAPAN_TB_CAUHOI", "TB_CAUHOI").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_CAUHOI> TB_CAUHOIReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_CAUHOI>("DB_TRACNGHIEMModel.FK_TB_DAPAN_TB_CAUHOI", "TB_CAUHOI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_CAUHOI>("DB_TRACNGHIEMModel.FK_TB_DAPAN_TB_CAUHOI", "TB_CAUHOI", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_TRACNGHIEMModel", Name="TB_KETQUA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_KETQUA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_KETQUA object.
        /// </summary>
        /// <param name="mAKQ">Initial value of the MAKQ property.</param>
        public static TB_KETQUA CreateTB_KETQUA(global::System.Int32 mAKQ)
        {
            TB_KETQUA tB_KETQUA = new TB_KETQUA();
            tB_KETQUA.MAKQ = mAKQ;
            return tB_KETQUA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MAKQ
        {
            get
            {
                return _MAKQ;
            }
            set
            {
                if (_MAKQ != value)
                {
                    OnMAKQChanging(value);
                    ReportPropertyChanging("MAKQ");
                    _MAKQ = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MAKQ");
                    OnMAKQChanged();
                }
            }
        }
        private global::System.Int32 _MAKQ;
        partial void OnMAKQChanging(global::System.Int32 value);
        partial void OnMAKQChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MATHISINH
        {
            get
            {
                return _MATHISINH;
            }
            set
            {
                OnMATHISINHChanging(value);
                ReportPropertyChanging("MATHISINH");
                _MATHISINH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MATHISINH");
                OnMATHISINHChanged();
            }
        }
        private global::System.String _MATHISINH;
        partial void OnMATHISINHChanging(global::System.String value);
        partial void OnMATHISINHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENTHISINH
        {
            get
            {
                return _TENTHISINH;
            }
            set
            {
                OnTENTHISINHChanging(value);
                ReportPropertyChanging("TENTHISINH");
                _TENTHISINH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TENTHISINH");
                OnTENTHISINHChanged();
            }
        }
        private global::System.String _TENTHISINH;
        partial void OnTENTHISINHChanging(global::System.String value);
        partial void OnTENTHISINHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MAMON
        {
            get
            {
                return _MAMON;
            }
            set
            {
                OnMAMONChanging(value);
                ReportPropertyChanging("MAMON");
                _MAMON = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MAMON");
                OnMAMONChanged();
            }
        }
        private global::System.String _MAMON;
        partial void OnMAMONChanging(global::System.String value);
        partial void OnMAMONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> DIEM
        {
            get
            {
                return _DIEM;
            }
            set
            {
                OnDIEMChanging(value);
                ReportPropertyChanging("DIEM");
                _DIEM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DIEM");
                OnDIEMChanged();
            }
        }
        private Nullable<global::System.Single> _DIEM;
        partial void OnDIEMChanging(Nullable<global::System.Single> value);
        partial void OnDIEMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NGAYTHI
        {
            get
            {
                return _NGAYTHI;
            }
            set
            {
                OnNGAYTHIChanging(value);
                ReportPropertyChanging("NGAYTHI");
                _NGAYTHI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NGAYTHI");
                OnNGAYTHIChanged();
            }
        }
        private global::System.String _NGAYTHI;
        partial void OnNGAYTHIChanging(global::System.String value);
        partial void OnNGAYTHIChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_TRACNGHIEMModel", "FK_TB_KETQUA_TB_MONTHI", "TB_MONTHI")]
        public TB_MONTHI TB_MONTHI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_MONTHI>("DB_TRACNGHIEMModel.FK_TB_KETQUA_TB_MONTHI", "TB_MONTHI").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_MONTHI>("DB_TRACNGHIEMModel.FK_TB_KETQUA_TB_MONTHI", "TB_MONTHI").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_MONTHI> TB_MONTHIReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_MONTHI>("DB_TRACNGHIEMModel.FK_TB_KETQUA_TB_MONTHI", "TB_MONTHI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_MONTHI>("DB_TRACNGHIEMModel.FK_TB_KETQUA_TB_MONTHI", "TB_MONTHI", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_TRACNGHIEMModel", "FK_TB_KETQUA_TB_THISINH", "TB_THISINH")]
        public TB_THISINH TB_THISINH
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_THISINH>("DB_TRACNGHIEMModel.FK_TB_KETQUA_TB_THISINH", "TB_THISINH").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_THISINH>("DB_TRACNGHIEMModel.FK_TB_KETQUA_TB_THISINH", "TB_THISINH").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_THISINH> TB_THISINHReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_THISINH>("DB_TRACNGHIEMModel.FK_TB_KETQUA_TB_THISINH", "TB_THISINH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_THISINH>("DB_TRACNGHIEMModel.FK_TB_KETQUA_TB_THISINH", "TB_THISINH", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_TRACNGHIEMModel", Name="TB_MONTHI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_MONTHI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_MONTHI object.
        /// </summary>
        /// <param name="mAMON">Initial value of the MAMON property.</param>
        /// <param name="tENMON">Initial value of the TENMON property.</param>
        public static TB_MONTHI CreateTB_MONTHI(global::System.String mAMON, global::System.String tENMON)
        {
            TB_MONTHI tB_MONTHI = new TB_MONTHI();
            tB_MONTHI.MAMON = mAMON;
            tB_MONTHI.TENMON = tENMON;
            return tB_MONTHI;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAMON
        {
            get
            {
                return _MAMON;
            }
            set
            {
                if (_MAMON != value)
                {
                    OnMAMONChanging(value);
                    ReportPropertyChanging("MAMON");
                    _MAMON = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MAMON");
                    OnMAMONChanged();
                }
            }
        }
        private global::System.String _MAMON;
        partial void OnMAMONChanging(global::System.String value);
        partial void OnMAMONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TENMON
        {
            get
            {
                return _TENMON;
            }
            set
            {
                OnTENMONChanging(value);
                ReportPropertyChanging("TENMON");
                _TENMON = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TENMON");
                OnTENMONChanged();
            }
        }
        private global::System.String _TENMON;
        partial void OnTENMONChanging(global::System.String value);
        partial void OnTENMONChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_TRACNGHIEMModel", "FK_TB_CAUHOI_TB_MONTHI", "TB_CAUHOI")]
        public EntityCollection<TB_CAUHOI> TB_CAUHOI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_CAUHOI>("DB_TRACNGHIEMModel.FK_TB_CAUHOI_TB_MONTHI", "TB_CAUHOI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_CAUHOI>("DB_TRACNGHIEMModel.FK_TB_CAUHOI_TB_MONTHI", "TB_CAUHOI", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_TRACNGHIEMModel", "FK_TB_KETQUA_TB_MONTHI", "TB_KETQUA")]
        public EntityCollection<TB_KETQUA> TB_KETQUA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_KETQUA>("DB_TRACNGHIEMModel.FK_TB_KETQUA_TB_MONTHI", "TB_KETQUA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_KETQUA>("DB_TRACNGHIEMModel.FK_TB_KETQUA_TB_MONTHI", "TB_KETQUA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_TRACNGHIEMModel", Name="TB_NHANVIEN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_NHANVIEN : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_NHANVIEN object.
        /// </summary>
        /// <param name="mANHANVIEN">Initial value of the MANHANVIEN property.</param>
        public static TB_NHANVIEN CreateTB_NHANVIEN(global::System.String mANHANVIEN)
        {
            TB_NHANVIEN tB_NHANVIEN = new TB_NHANVIEN();
            tB_NHANVIEN.MANHANVIEN = mANHANVIEN;
            return tB_NHANVIEN;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MANHANVIEN
        {
            get
            {
                return _MANHANVIEN;
            }
            set
            {
                if (_MANHANVIEN != value)
                {
                    OnMANHANVIENChanging(value);
                    ReportPropertyChanging("MANHANVIEN");
                    _MANHANVIEN = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MANHANVIEN");
                    OnMANHANVIENChanged();
                }
            }
        }
        private global::System.String _MANHANVIEN;
        partial void OnMANHANVIENChanging(global::System.String value);
        partial void OnMANHANVIENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HOTEN
        {
            get
            {
                return _HOTEN;
            }
            set
            {
                OnHOTENChanging(value);
                ReportPropertyChanging("HOTEN");
                _HOTEN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HOTEN");
                OnHOTENChanged();
            }
        }
        private global::System.String _HOTEN;
        partial void OnHOTENChanging(global::System.String value);
        partial void OnHOTENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TENDN
        {
            get
            {
                return _TENDN;
            }
            set
            {
                OnTENDNChanging(value);
                ReportPropertyChanging("TENDN");
                _TENDN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TENDN");
                OnTENDNChanged();
            }
        }
        private global::System.String _TENDN;
        partial void OnTENDNChanging(global::System.String value);
        partial void OnTENDNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MATKHAU
        {
            get
            {
                return _MATKHAU;
            }
            set
            {
                OnMATKHAUChanging(value);
                ReportPropertyChanging("MATKHAU");
                _MATKHAU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MATKHAU");
                OnMATKHAUChanged();
            }
        }
        private global::System.String _MATKHAU;
        partial void OnMATKHAUChanging(global::System.String value);
        partial void OnMATKHAUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CHUCVU
        {
            get
            {
                return _CHUCVU;
            }
            set
            {
                OnCHUCVUChanging(value);
                ReportPropertyChanging("CHUCVU");
                _CHUCVU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CHUCVU");
                OnCHUCVUChanged();
            }
        }
        private global::System.String _CHUCVU;
        partial void OnCHUCVUChanging(global::System.String value);
        partial void OnCHUCVUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DIACHI
        {
            get
            {
                return _DIACHI;
            }
            set
            {
                OnDIACHIChanging(value);
                ReportPropertyChanging("DIACHI");
                _DIACHI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DIACHI");
                OnDIACHIChanged();
            }
        }
        private global::System.String _DIACHI;
        partial void OnDIACHIChanging(global::System.String value);
        partial void OnDIACHIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SODIENTHOAI
        {
            get
            {
                return _SODIENTHOAI;
            }
            set
            {
                OnSODIENTHOAIChanging(value);
                ReportPropertyChanging("SODIENTHOAI");
                _SODIENTHOAI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SODIENTHOAI");
                OnSODIENTHOAIChanged();
            }
        }
        private global::System.String _SODIENTHOAI;
        partial void OnSODIENTHOAIChanging(global::System.String value);
        partial void OnSODIENTHOAIChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_TRACNGHIEMModel", "FK_TB_CAUHOI_TB_NHANVIEN", "TB_CAUHOI")]
        public EntityCollection<TB_CAUHOI> TB_CAUHOI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_CAUHOI>("DB_TRACNGHIEMModel.FK_TB_CAUHOI_TB_NHANVIEN", "TB_CAUHOI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_CAUHOI>("DB_TRACNGHIEMModel.FK_TB_CAUHOI_TB_NHANVIEN", "TB_CAUHOI", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_TRACNGHIEMModel", Name="TB_THISINH")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_THISINH : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_THISINH object.
        /// </summary>
        /// <param name="mATHISINH">Initial value of the MATHISINH property.</param>
        /// <param name="tENDN">Initial value of the TENDN property.</param>
        /// <param name="mATKHAU">Initial value of the MATKHAU property.</param>
        public static TB_THISINH CreateTB_THISINH(global::System.String mATHISINH, global::System.String tENDN, global::System.String mATKHAU)
        {
            TB_THISINH tB_THISINH = new TB_THISINH();
            tB_THISINH.MATHISINH = mATHISINH;
            tB_THISINH.TENDN = tENDN;
            tB_THISINH.MATKHAU = mATKHAU;
            return tB_THISINH;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MATHISINH
        {
            get
            {
                return _MATHISINH;
            }
            set
            {
                if (_MATHISINH != value)
                {
                    OnMATHISINHChanging(value);
                    ReportPropertyChanging("MATHISINH");
                    _MATHISINH = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MATHISINH");
                    OnMATHISINHChanged();
                }
            }
        }
        private global::System.String _MATHISINH;
        partial void OnMATHISINHChanging(global::System.String value);
        partial void OnMATHISINHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HOTEN
        {
            get
            {
                return _HOTEN;
            }
            set
            {
                OnHOTENChanging(value);
                ReportPropertyChanging("HOTEN");
                _HOTEN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HOTEN");
                OnHOTENChanged();
            }
        }
        private global::System.String _HOTEN;
        partial void OnHOTENChanging(global::System.String value);
        partial void OnHOTENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TENDN
        {
            get
            {
                return _TENDN;
            }
            set
            {
                OnTENDNChanging(value);
                ReportPropertyChanging("TENDN");
                _TENDN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TENDN");
                OnTENDNChanged();
            }
        }
        private global::System.String _TENDN;
        partial void OnTENDNChanging(global::System.String value);
        partial void OnTENDNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MATKHAU
        {
            get
            {
                return _MATKHAU;
            }
            set
            {
                OnMATKHAUChanging(value);
                ReportPropertyChanging("MATKHAU");
                _MATKHAU = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MATKHAU");
                OnMATKHAUChanged();
            }
        }
        private global::System.String _MATKHAU;
        partial void OnMATKHAUChanging(global::System.String value);
        partial void OnMATKHAUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DIACHI
        {
            get
            {
                return _DIACHI;
            }
            set
            {
                OnDIACHIChanging(value);
                ReportPropertyChanging("DIACHI");
                _DIACHI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DIACHI");
                OnDIACHIChanged();
            }
        }
        private global::System.String _DIACHI;
        partial void OnDIACHIChanging(global::System.String value);
        partial void OnDIACHIChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_TRACNGHIEMModel", "FK_TB_KETQUA_TB_THISINH", "TB_KETQUA")]
        public EntityCollection<TB_KETQUA> TB_KETQUA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_KETQUA>("DB_TRACNGHIEMModel.FK_TB_KETQUA_TB_THISINH", "TB_KETQUA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_KETQUA>("DB_TRACNGHIEMModel.FK_TB_KETQUA_TB_THISINH", "TB_KETQUA", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
